UH-StudentServices/student_guide

config/sync/language/fi/views.view.themes.yml
config/sync/language/sv/views.view.themes.yml
modules/uhsg_migrate/artifacts/themes.csv
modules/uhsg_migrate/artifacts/themes_translation.csv

This PR is an update for the CSV files that gets migrated for initial contents. This also translates the view title displayed in frontapge that wasn't originally translated.
After pulling this branch, you may run `drush mi --all --update` to update your existing content.

HUB-48: Translations

---

CHANGELOG.md
config/sync/core.entity_form_display.user.user.default.yml
config/sync/core.entity_view_display.user.user.default.yml
config/sync/core.extension.yml
config/sync/field.field.user.user.field_student_number.yml
config/sync/field.storage.user.field_student_number.yml
config/sync/uhsg_user_sync.settings.yml
modules/uhsg_oprek/config/schema/uhsg_oprek.settings.schema.yml
modules/uhsg_oprek/src/Controller/OprekController.php
modules/uhsg_oprek/src/Oprek/OprekService.php
modules/uhsg_oprek/src/Oprek/OprekServiceInterface.php
modules/uhsg_oprek/uhsg_oprek.info.yml
modules/uhsg_oprek/uhsg_oprek.links.task.yml
modules/uhsg_oprek/uhsg_oprek.permissions.yml
modules/uhsg_oprek/uhsg_oprek.routing.yml
modules/uhsg_oprek/uhsg_oprek.services.yml
modules/uhsg_user_sync/config/install/uhsg_user_sync.settings.yml
modules/uhsg_user_sync/config/schema/uhsg_user_sync.schema.yml
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriberFactory.php
modules/uhsg_user_sync/uhsg_user_sync.info.yml
modules/uhsg_user_sync/uhsg_user_sync.services.yml

* Oprek module provides:
* Service for getting study rights
* Restricted permissions for viewing oprek info
* Task page that presents what oprek gives us for given users with student numbers
* User sync synchronises student number to `field_student_number` field

HUB-135: Oprek tool

---

config/sync/core.entity_form_display.flagging.my_degree_programmes.default.yml
config/sync/core.entity_form_display.taxonomy_term.degree_programme.default.yml
config/sync/core.entity_view_display.flagging.my_degree_programmes.default.yml
config/sync/core.entity_view_display.taxonomy_term.degree_programme.default.yml
config/sync/field.field.flagging.my_degree_programmes.field_applied_by_study_rights.yml
config/sync/field.field.flagging.my_degree_programmes.field_primary.yml
config/sync/field.field.taxonomy_term.degree_programme.field_code.yml
config/sync/field.storage.flagging.field_applied_by_study_rights.yml
config/sync/field.storage.flagging.field_primary.yml
config/sync/field.storage.taxonomy_term.field_code.yml
config/sync/language/fi/field.field.taxonomy_term.degree_programme.field_code.yml
config/sync/migrate_plus.migration.degree_programmes.yml
config/sync/migrate_plus.migration.degree_programmes_translation.yml
modules/uhsg_migrate/config/install/migrate_plus.migration.degree_programmes.yml
modules/uhsg_migrate/config/install/migrate_plus.migration.degree_programmes_translation.yml
modules/uhsg_oprek/config/install/uhsg_oprek.settings.yml
modules/uhsg_oprek/config/schema/uhsg_oprek.settings.schema.yml
modules/uhsg_oprek/src/Oprek/OprekService.php
modules/uhsg_oprek/src/Oprek/OprekServiceInterface.php
modules/uhsg_oprek/src/Oprek/StudyRight/Element.php
modules/uhsg_oprek/src/Oprek/StudyRight/ElementInterface.php
modules/uhsg_oprek/src/Oprek/StudyRight/StudyRight.php
modules/uhsg_oprek/src/Oprek/StudyRight/StudyRightInterface.php
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriberFactory.php

When user logs in, it should create `my degree programme` flaggings automatically. This PR wont still accomplish the ticket requirements, so further development is still needed.
* Creates fields to flagging: `field_primary` and `field_applied_by_study_rights`
* Adds degree programme sync in `\Drupal\uhsg_user_sync\SamlAuth\UserSyncSubscriber::onUserSync`
* Added/improved features for `\Drupal\uhsg_oprek\Oprek\OprekService` to accomplish the syncing feature

HUB-56: First phase / syncing degree programmes

---

CHANGELOG.md
config/sync/uhsg_active_degree_programme.settings.yml
modules/uhsg_active_degree_programme/config/install/uhsg_active_degree_programme.settings.yml
modules/uhsg_active_degree_programme/config/schema/uhsg_active_degree_programme.settings.schema.yml
modules/uhsg_active_degree_programme/src/ActiveDegreeProgrammeService.php
modules/uhsg_active_degree_programme/uhsg_active_degree_programme.info.yml
modules/uhsg_active_degree_programme/uhsg_active_degree_programme.services.yml

This PR will make active degree programme logic to fall back to the primary degree programme that is synchronised from oprek integration during the login.

HUB-56, HUB-58: Finalise active degree programme logic

---

CHANGELOG.md
modules/uhsg_office_hours/js/officeHours.js
modules/uhsg_office_hours/src/OfficeHoursService.php
themes/uhsg_theme/templates/paragraphs/paragraph--office-hours.html.twig
translations/fi.po
translations/sv.po

Implements support for "general" office hours that are not degree programme specific. Concrete use case will be the office hours for the Language Centre.
- The general office hours are always displayed
- Degree programme specific office hours are still displayed only when their degree programme matches the active degree programme
- Both the degree programme and language centre specific office hours are contained in an accordion element
- Each accordion is visible only when there are relevant office hours (otherwise hidden)
- The degree programme specific accordion is active (open) by default
- The language centre specific accordion is closed by default
Since there is no general office hour support built in My Teaching yet, the only way to test this functionality is to mock the office hour …

HUB-245: Language Centre office hours support.

---

CHANGELOG.md
config/sync/language/fi/system.site.yml
config/sync/language/sv/system.site.yml
config/sync/migrate_plus.migration_group.uhsg_initials.yml
config/sync/system.site.yml
modules/uhsg_feedback/uhsg_feedback.module
modules/uhsg_migrate/artifacts/menu_links.csv
modules/uhsg_news/src/Controller/NewsFeedController.php

HUB-242: Site name change

---

CHANGELOG.md
modules/uhsg_redirect_to_login/src/Routing/RouteSubscriber.php
modules/uhsg_redirect_to_login/uhsg_redirect_to_login.services.yml

Things to test:
* How redirection work from different pages
* How login works when you were logged in previously as another user
* Any PHP notices during the process?

HUB-246: Allow redirect login to happen even with logged in users

---

CHANGELOG.md
composer.json
composer.lock
config/sync/image.style.image_full_width.yml
config/sync/image.style.news_teaser_image.yml
config/sync/image.style.theme_teaser_image_desktop.yml
config/sync/image.style.theme_teaser_image_mobile.yml
config/sync/image.style.theme_teaser_image_tablet.yml

- Core and core dependencies
- Required PHPUnit upgrade (4 -> 6) and dependencies
- Removed a redundant core patch

Feature/hub 348 drupal core 8.6.1

---

composer.lock

```
Package operations: 4 installs, 20 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
- Installing pear/pear_exception (v1.0.0): Downloading (100%)         
- Installing pear/console_getopt (v1.4.2): Downloading (100%)         
- Installing pear/pear-core-minimal (v1.10.9): Downloading (100%)         
- Installing pear/archive_tar (1.4.7): Downloading (100%)         
- Updating symfony/http-foundation (v3.4.23 => v3.4.27): Downloading (100%)         
- Updating symfony/event-dispatcher (v3.4.23 => v3.4.27): Downloading (100%)         
- Updating symfony/debug (v4.2.4 => v4.2.8): Downloading (100%)         
- Updating symfony/http-kernel (v3.4.23 => v3.4.27): Downloading (100%)         
- Updating …
```

Drupal core update

---

composer.json
composer.lock
config/sync/block.block.mainmenuen.yml
config/sync/block.block.mainmenufi.yml
config/sync/block.block.mainmenusv.yml
config/sync/core.extension.yml
modules/uhsg_obar/config/install/uhsg_obar.settings.yml
modules/uhsg_obar/config/schema/uhsg_obar.settings.schema.yml
modules/uhsg_obar/js/obar.js
modules/uhsg_obar/src/Jwt.php
modules/uhsg_obar/uhsg_obar.info.yml
modules/uhsg_obar/uhsg_obar.libraries.yml
modules/uhsg_obar/uhsg_obar.module
modules/uhsg_obar/uhsg_obar.services.yml
package-lock.json
student_guide.info.yml
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_header_obar.scss
themes/uhsg_theme/templates/layout/page.html.twig
themes/uhsg_theme/templates/layout/region--header--obar.html.twig
themes/uhsg_theme/templates/layout/region--header.html.twig

This change will inject theme suggestion for theme region. This theme suggestion gets picked up by theme and sets Obar header mounting `div`. Drupal must place blocks on the "header" region in order to render the region (and pick up the Obar template), hence the blocks are not been removed from "header" region, even they are not intended to be shown.
Module will generate JWT value containing all required attributes for Obar to function properly.
In order to work, you must use/create private/public key and configure it to `settings.php`.

HUB-409: Obar

---

CHANGELOG.md
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_logo.scss
themes/uhsg_theme/sass/style.scss
themes/uhsg_theme/templates/layout/region--header.html.twig
themes/uhsg_theme/uhsg_theme.theme

The image link will now take to helsinki.fi frontpage, and text part will be taking to frontpage of instructions for teaching.

HUB-457: Change logo text to link to <front>

---

CHANGELOG.md
modules/uhsg_obar/uhsg_obar.info.yml
modules/uhsg_obar/uhsg_obar.module
themes/uhsg_theme/sass/components/_header_obar.scss
themes/uhsg_theme/templates/layout/region--footer--obar.html.twig

This is my first attempt, may need further finetuning.
The black area seems to work as expected (see https://wiki.helsinki.fi/display/d/Footer ). 
The gray area is to be implemented later(?).

HUB-621 - Added obar footer functionality.

---

config/sync/field.storage.taxonomy_term.field_degree_programme_type.yml
config/sync/language/fi/field.storage.taxonomy_term.field_degree_programme_type.yml
config/sync/language/sv/field.storage.taxonomy_term.field_degree_programme_type.yml
modules/uhsg_degree_programme/src/Plugin/views/sort/DegreeProgrammeType.php

- Added new selection option to field_degree_programme_type (with translations).
- Updated programme type sorting plugin to include the new option and place it at the bottom.

HUB-656: Specialist training programme type

---

themes/uhsg_theme/js/siteimprove.js
themes/uhsg_theme/uhsg_theme.info.yml
themes/uhsg_theme/uhsg_theme.libraries.yml

* Add siteimprove script as a custom js library under theme.
Test:
* build
* check html-code and verify that siteimprove.js has been added.

HUB-700 - add siteimprove script

---

composer.lock

This PR updates Drupal core from 8.8.8 to 8.8.10 and fixes multiple security vulnerabilities listed here: https://www.drupal.org/project/drupal/releases/8.8.10

HUB-769: Updating Drupal core from 8.8.8 to 8.8.10.

---

themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/common-elements/_common-elements.scss
themes/uhsg_theme/sass/components/_textarea.scss
themes/uhsg_theme/sass/variables/_variables.scss

This PR updates link element styles by changing the colour and adding an underline. The change only affects link elements inside content text, not generic UI elements using the link element.

HUB-723: Updating the link element styles.

---

themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_misc.scss
themes/uhsg_theme/sass/components/_tabs.scss
themes/uhsg_theme/sass/mixins/_utils.scss
themes/uhsg_theme/templates/block/block--themes-per-user-group.html.twig
translations/fi.po
translations/sv.po

This PR adds an accordion header to frontpage tab container that is only visible when the accordion mode is active (mobile viewport).

HUB-765: Accordion title

---

modules/uhsg_sisu/README.md
modules/uhsg_sisu/src/Services/SisuService.php
modules/uhsg_sisu/src/Services/StudyRightsService.php
modules/uhsg_sisu/uhsg_sisu.services.yml
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php

Add settings and make better use of logging so that we can have sisu and oodi work both and switch between them.

HUB-667 - sisu integration

---

composer.json
composer.lock

Add entity_browser module which, while missing, prevented running tests on paragraph module, and thus the whole project. This PR is only for fixing the issue of running tests. We have multiple tests that fail because they haven't been updated, we need to make a new ticket for that separately.

HUB-451 - Add entity_browser module

---

CHANGELOG.md
themes/uhsg_theme/js/degreeProgrammeSwitcher.js
themes/uhsg_theme/js/otherEducationProviderSwitcher.js
themes/uhsg_theme/templates/block/block--views-block--degree-programmes-block-1.html.twig
themes/uhsg_theme/templates/block/block--views-block--other-education-providers-block-1.html.twig
themes/uhsg_theme/uhsg_theme.theme

This PR adds a couple more accessibility improvements to degree programme and other education provider selections:
- Removing the autofocus on degree programme filter search input when opening the selection
- Updating reset link from a link element to a button.

HUB-784: Degree programme and other education provider selection a11y improvements

---

CHANGELOG.md
themes/uhsg_theme/uhsg_theme.theme

This PR adds an interface language parameter with current language code to YouTube embed url's.

HUB-767: Video embed a11y

---

CHANGELOG.md
themes/uhsg_theme/css/style.css
themes/uhsg_theme/js/degreeProgrammeSwitcher.js
themes/uhsg_theme/js/otherEducationProviderSwitcher.js
themes/uhsg_theme/sass/components/_degree-programme-switcher.scss
themes/uhsg_theme/sass/components/_other-education-provider-switcher.scss

This PR reverts changes introduced in https://github.com/UH-StudentServices/student_guide/pull/376 . It was decided the fix there was decreasing usability to a large user group while improving it to only a very few.

HUB-785: Revert changes introduced in pull request #376

---

composer.json
composer.lock

* Update core + required libraries to newest 8.9.x version.

HUB-798 - Update core

---

modules/uhsg_obar/src/Jwt.php
modules/uhsg_obar/tests/src/Unit/JwtTest.php
modules/uhsg_office_hours/tests/src/Unit/OfficeHoursServiceTest.php
modules/uhsg_sisu/src/Services/StudyRightsService.php
modules/uhsg_sisu/src/Services/StudyRightsServiceInterface.php
modules/uhsg_themes/src/Plugin/Block/ThemesReferencingInstructions.php
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php
modules/uhsg_user_sync/tests/src/Unit/SamlAuth/UserSyncSubscriberTest.php

* This will fix all current unit tests.
* There are some questionable fixes, need to look into them more after drupal 9.0 update which also requires custom code updates and will require reworking tests again. But for now, we have functional unit tests.

HUB-786 fixing unit tests

---

themes/uhsg_theme/templates/node/node--news--full.html.twig

Do not show degree_programme_switcher if we are in "Tiedote" content type.

HUB-801 - Remove degree_programme_switcher from "tiedote"

---

config/sync/user.role.content_owner.yml

* Add break content lock permission to content owner.

HUB-802 - Content Owner Permissions

---

CHANGELOG.md
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_links.scss
themes/uhsg_theme/sass/components/_main-menu.scss
themes/uhsg_theme/sass/components/_tabs.scss
themes/uhsg_theme/sass/layout/_layout.scss
themes/uhsg_theme/sass/layout/common/_l-footer.scss
themes/uhsg_theme/sass/layout/common/_l-subregion.scss
themes/uhsg_theme/sass/layout/common/_l-top-bar.scss
themes/uhsg_theme/sass/style.scss
themes/uhsg_theme/sass/styleguide-overrides/variables/_breakpoints.scss
themes/uhsg_theme/sass/variables/_variables.scss
themes/uhsg_theme/templates/navigation/menu--main.html.twig

This PR updates styles to match the page width and margins of Studies service.

HUB-696: Unifying margins with Studies service

---

CHANGELOG.md
config/sync/core.entity_form_display.user.user.default.yml
config/sync/core.entity_view_display.user.user.default.yml
config/sync/field.field.user.user.field_employee_number.yml
config/sync/field.storage.user.field_employee_number.yml
config/sync/uhsg_user_sync.settings.yml
modules/uhsg_obar/src/Jwt.php
modules/uhsg_samlauth/src/AttributeParser.php
modules/uhsg_user_sync/config/install/uhsg_user_sync.settings.yml
modules/uhsg_user_sync/config/schema/uhsg_user_sync.settings.schema.yml
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php

This PR updates Obar configuration to:
- Remove the application specific footer
- Add user roles data based on student and/or employee number

HUB-825: Obar configuration changes

---

CHANGELOG.md
modules/uhsg_themes/src/Plugin/Block/ThemesReferencingInstructions.php
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_copy_url_button.scss
themes/uhsg_theme/uhsg_theme.theme

This PR fixes a bug where node revision view would throw a php error on some occasions. This also fixes a layout bug on that same view.

HUB-830: Revision view bug fix

---

config/sync/image.style.theme_teaser_image_desktop.yml
config/sync/image.style.theme_teaser_image_mobile.yml
config/sync/image.style.theme_teaser_image_tablet.yml
config/sync/responsive_image.styles.theme_teaser_image.yml
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_theme.scss
themes/uhsg_theme/sass/layout/_layout.scss
themes/uhsg_theme/sass/layout/common/_l-subregion.scss
themes/uhsg_theme/uhsg_theme.breakpoints.yml

This PR updates the frontpage theme box layout to better match the new max page with and breakpoints.

HUB-696: Theme box layout

---

modules/uhsg_active_degree_programme/src/ActiveDegreeProgrammeService.php
modules/uhsg_active_degree_programme/src/Cache/Context/ActiveDegreeProgrammeCacheContext.php

* Modify cache context headers properly. Remove fetching degree_programme from headers since it will interfere with cache context.

HUB-800 - Cache modifications

---

modules/uhsg_active_degree_programme/src/ActiveDegreeProgrammeService.php

* This will allow us to bypass term handling when data has already been saved.

HUB-800 - Bypass term resolving for filtering purposes.

---

modules/uhsg_rest/src/Plugin/rest/resource/DegreeProgrammeResource.php

* This will add programme_type to rest results.

HUB-840 - Add programme type to rest results.

---

CHANGELOG.md
config/sync/views.view.themes.yml
modules/uhsg_search/js/filterSearch.js
modules/uhsg_themes/src/Plugin/Block/ThemesPerUserGroup.php
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_tabs.scss
themes/uhsg_theme/sass/variables/_variables.scss
themes/uhsg_theme/templates/block/block--themes-per-user-group.html.twig
translations/fi.po
translations/sv.po

This PR updates some UI elements with support for Open University content:
- Front page theme tabs
- Search filters
Also the theme tabs color is updated to increase accessibility.

HUB-773: Open university UI elements

---

CHANGELOG.md
config/sync/block.block.breadcrumbs.yml
config/sync/core.extension.yml
config/sync/language/fi/uhsg_service_provider_details.settings.yml
config/sync/language/sv/uhsg_service_provider_details.settings.yml
config/sync/uhsg_service_provider_details.settings.yml
modules/uhsg_breadcrumb/src/UhsgBreadcrumbBuilder.php
modules/uhsg_breadcrumb/src/UhsgPathBasedBreadcrumbBuilder.php
modules/uhsg_breadcrumb/uhsg_breadcrumb.info.yml
modules/uhsg_breadcrumb/uhsg_breadcrumb.services.yml
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_breadcrumbs.scss
themes/uhsg_theme/sass/functions/_utils.scss
themes/uhsg_theme/sass/style.scss
themes/uhsg_theme/templates/navigation/breadcrumb.html.twig
themes/uhsg_theme/uhsg_theme.theme

This PR updates the breadcrumb to better match the common UX of Studies service.

HUB-693: Breadcrumb

---

CHANGELOG.md
composer.lock

This PR updates Drupal core 8.9.13.

HUB-835: Drupal core security update

---

modules/uhsg_sisu/src/Services/StudyRightsService.php
modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php

Handle sisu results from graphql properly.
* Replace a few indentations here and there.
* Proper name handling based on GraphQL results.
```
{
"data": {
"private_person": {
"studyRightPrimalityChain": {
"studyRightPrimalities": [
{
"studyRightId": "hy-opinoik-139365914",
"startDate": "2020-10-29",
"endDate": null,
"documentState": "ACTIVE"
}
]
},
"studyRights": [
{
"id": "hy-opinoik-139365914",
"valid": {
"startDate": "2019-08-01",
"endDate": "2023-08-01"
},
"studyRightGraduation": null,
"acceptedSelectionPath": {
"educationPhase1Child": {
"code": "EDUM-LO-KT",
"groupId": "otm-803f1277-54a5-401a-a934-02f42798c827",
"name": {
"fi": "Luokanopettaja, kasvatustiede",
"sv": "Klasslärare, pedagogik",
"en": "Class Teacher, Education"
}
},
"educationPhase1": {
"code": "MH60_001",
"groupId": …
```

HUB-776 - Handle sisu results properly.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/jsonapi_image_styles.settings.yml

* Startup local env and go http://local.guide.student.helsinki.fi/ohjeet/jsonapi/node/news
* Find content that has a image file like so:
```
"field_news_image": {
"data": {
"type": "file--file",
"id": "42169a1d-e6d1-414d-ba52-3c3d679c3289",
"meta": {
"alt": "Automated test news 0216250cb53c",
"title": "",
"width": 735,
"height": 735
}
},
"links": {
"related": {
"href": "http://local.guide.student.helsinki.fi/ohjeet/jsonapi/node/news/0877d8ce-64a6-4a8e-a0ad-bc434748e93b/field_news_image?resourceVersion=id%3A261"
},
"self": {
"href": "http://local.guide.student.helsinki.fi/ohjeet/jsonapi/node/news/0877d8ce-64a6-4a8e-a0ad-bc434748e93b/relationships/field_news_image?resourceVersion=id%3A261"
}
}
}
```
* Click related and make sure that imagestyle_uri has been added to results:
``` …
```

HUB-833 jsonapi imagestyles

---

CHANGELOG.md
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/common-elements/_common-elements.scss
themes/uhsg_theme/sass/style.scss
themes/uhsg_theme/sass/styleguide-overrides/variables/_typography.scss
themes/uhsg_theme/templates/dataset/item-list.html.twig
themes/uhsg_theme/templates/fields/field--field-article-paragraph.html.twig
themes/uhsg_theme/templates/paragraphs/paragraph--eduviewer.html.twig
themes/uhsg_theme/templates/paragraphs/paragraph--office-hours.html.twig
themes/uhsg_theme/templates/paragraphs/paragraph--paragraph.html.twig
translations/fi.po
translations/sv.po

This PR updates heading font sizes and adjusts the heading levels used in different elements to ensure proper hierarchy.

HUB-760: Heading hierarchy and font sizes

---

CHANGELOG.md
composer.json
composer.lock
config/sync/core.extension.yml

* this will add openapi modules to generate swagger specs. Will hold for merging if need be to do more coding additionally to these.

HUB-854 openapi description

---

CHANGELOG.md
config/sync/block.block.contactblock.yml
config/sync/block.block.linktoinstructionsforstudents.yml
config/sync/block.block.newsperdegreeprogramme.yml
config/sync/block.block.newsperdoctoralprogramme.yml
config/sync/core.entity_view_display.node.article.teaser.yml
config/sync/core.extension.yml
config/sync/language/fi/block.block.linktoinstructionsforstudents.yml
config/sync/language/sv/block.block.linktoinstructionsforstudents.yml
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_block-link-to-instructions-for-students.scss
themes/uhsg_theme/sass/components/_breadcrumbs.scss
themes/uhsg_theme/sass/layout/_layout.scss
themes/uhsg_theme/sass/variables/_variables.scss
themes/uhsg_theme/templates/block/block--link-to-instructions-for-students.html.twig
themes/uhsg_theme/templates/node/node--article--full.html.twig
themes/uhsg_theme/templates/node/node--theme--full.html.twig
themes/uhsg_theme/uhsg_theme.theme

This PR updates the position of "See also" links block.

HUB-730: Teaching related links update

---

CHANGELOG.md
student_guide.install
student_guide.profile
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_degree-programme-switcher.scss
themes/uhsg_theme/templates/block/block--views-block--degree-programmes-block-1.html.twig
themes/uhsg_theme/uhsg_theme.theme

This PR updates the degree programme selector markup and styles to move the reset button from the bottom to the top of the collapsed element. A block content based description text element is also added to allow administrative users to add/modify the contents on site.

HUB-718: Degree programme dropdown improvements

---

CHANGELOG.md
config/sync/core.entity_view_display.node.article.search_result.yml
config/sync/core.entity_view_display.node.news.search_result.yml
config/sync/core.entity_view_display.node.theme.search_result.yml
config/sync/core.entity_view_mode.node.search_result.yml
config/sync/language/fi/views.view.search.yml
config/sync/language/sv/views.view.search.yml
config/sync/views.view.search.yml
modules/uhsg_search/js/filterSearch.js
modules/uhsg_search/uhsg_search.module
modules/uhsg_translations/src/Helpers/TranslationHelper.php
modules/uhsg_translations/uhsg_translations.install
themes/uhsg_theme/css/style.css
themes/uhsg_theme/sass/components/_box_story.scss
themes/uhsg_theme/sass/components/_search.scss
themes/uhsg_theme/sass/layout/common/_l-subregion.scss
themes/uhsg_theme/sass/objects/_bar.scss
themes/uhsg_theme/sass/objects/_button.scss
themes/uhsg_theme/templates/block/block--views-block--news-by-active-degree-programme-block-1.html.twig
themes/uhsg_theme/templates/layout/page.html.twig
themes/uhsg_theme/templates/misc/pager.html.twig
themes/uhsg_theme/templates/node/node--search-result.html.twig
themes/uhsg_theme/templates/views/views-view--news-by-active-degree-programme.html.twig
themes/uhsg_theme/templates/views/views-view--news.html.twig
themes/uhsg_theme/templates/views/views-view--search.html.twig
themes/uhsg_theme/uhsg_theme.theme

This PR updates markup and styles for search results and the news archive.

HUB-722: Search result styles

---

CHANGELOG.md
composer.json
composer.lock

Clones https://github.com/wunderio/client-fi-uh-guide/pull/146.

HUB-868: Updating Composer to version 2.

---

CHANGELOG.md
composer.lock

This PR updates Drupal core from 8.9.14 to 8.9.16 to resolve security issue https://www.drupal.org/sa-core-2021-003 .

HUB-887: Updating Drupal core to 8.9.16.
