- CHANGELOG.md
- config/sync/core.extension.yml
- modules/uhsg_samlauth/src/Controller/SamlController.php
- modules/uhsg_samlauth/src/Routing/RouteSubscriber.php
- modules/uhsg_samlauth/src/SamlService.php
- modules/uhsg_samlauth/src/UhsgSamlauthServiceProvider.php
- modules/uhsg_samlauth/uhsg_samlauth.info.yml
- modules/uhsg_samlauth/uhsg_samlauth.services.yml
- student_guide.info.yml
This feature should always redirect back to the page where use used to be before logging in.
* Uses SAML Auth module as base for the functionality
* Swaps the original service to own service
* Swaps the origianl controller to own controller
* Own service has additional features for storing/reading and clearing the path where user comes from
* Own controller uses own overrided service that has features to deliver/control the redirect destinations
> HUB-96: Login/logout destinations

- config/sync/core.extension.yml
- config/sync/uhsg_degree_programme.settings.yml
- modules/uhsg_degree_programme/config/install/uhsg_degree_programme.settings.yml
- modules/uhsg_degree_programme/config/schema/uhsg_degree_programme.settings.schema.yml
- modules/uhsg_degree_programme/src/Flag/MyDegreeProgrammeFlagType.php
- modules/uhsg_degree_programme/uhsg_degree_programme.flag.inc
- modules/uhsg_degree_programme/uhsg_degree_programme.info.yml
- modules/uhsg_degree_programme/uhsg_degree_programme.module
* Moved non-activeness degree programme code to new module that holds some functionalities around degree programme (but not directly related to active degree programme)
* Alters & extends `EntityFlagType` to deny acces for flagging/unflagging when flag has been marked to be technical flagging
> DOO-56: Do not allow (un)flagging for technical flags

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/filter.format.filtered_html.yml
Alongside, while adding the repository via command. Some extra reformatting was taken place.
Also, video_embed_field needed to be updated to v1.5.
If you have major `composer.lock` conflict, check their head and re-type these commands to get same results as in this branch:
```
$ composer update video_embed_field
$ composer config repositories.video_embed_unitube vcs https://github.com/UH-StudentServices/video_embed_unitube
$ composer require composer require UH-StudentServices/video_embed_unitube:^v1.0-alpha1
```
> HUB-223: Added possibility to use UniTube links

- CHANGELOG.md
- config/sync/filter.format.filtered_html.yml
- modules/uhsg_active_degree_programme/src/ActiveDegreeProgrammeService.php
- modules/uhsg_active_degree_programme/uhsg_active_degree_programme.services.yml
- modules/uhsg_news/src/Controller/NewsFeedController.php
- modules/uhsg_news/src/Plugin/Block/NewsPerDegreeProgramme.php
- modules/uhsg_news/src/TargetedNewsService.php
- modules/uhsg_news/uhsg_news.info.yml
- modules/uhsg_news/uhsg_news.module
- modules/uhsg_news/uhsg_news.routing.yml
- modules/uhsg_news/uhsg_news.services.yml
* This feed is aware of active degree programme (cookies, headers or query parameter)
* Works centralized with same query as with news promotions at front page
* Active degree programme can be now set through query parameter with the code directly (`{URL}?degree_programme_code=KH57_001`)
Testing URL examples:
* https://local.guide.student.helsinki.fi/en/news/feed.xml?degree_programme_code=KH57_001
* https://local.guide.student.helsinki.fi/fi/news/feed.xml?degree_programme_code=KH57_001
* https://local.guide.student.helsinki.fi/sv/news/feed.xml?degree_programme_code=KH57_001
* https://local.guide.student.helsinki.fi/fi/news/feed.xml (just general news only)
* https://local.guide.student.helsinki.fi/fi/news/feed.xml?degree_programme=90 (if you would like to use term ids instead)
> HUB-234: Atom/RSS feed for news

- CHANGELOG.md
- modules/uhsg_avatar/src/AvatarService.php
Avoid unnecessary external API calls. Fetch the avatar only when the user has Oodi UID (required to fetch the avatar).
> HUB-249: Fetch avatar only when the user has Oodi UID.

- CHANGELOG.md
- modules/uhsg_oprek/config/install/uhsg_oprek.settings.yml
- modules/uhsg_oprek/config/schema/uhsg_oprek.settings.schema.yml
- modules/uhsg_oprek/src/Oprek/OprekService.php
* Download certificate and key file to your environment for testing (use SSH tunneling if needed)
* Change `base_url` configuration to prefix with `/secure` endpoint
* Configure your certificate file and key file paths for the module in `settings.local.php`
> HUB-319: Use certificate for oprek requests

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/field.field.node.news.body.yml
Tiedotteiden yhteenvetoa ei aina muisteta kirjoittaa kun kenttä pitäisi muistaa itse klikata auki. Ilman yhteenvetoa tiedotenäkymä venyy pitkäksi.
Ratkaisuksi pyritään käyttämään valmista yhteisömoduulia.
Moduuli ei ole virallisesti merkitty vakaaksi moduuliksi. Se on julkaistu vuonna 2017 Huhtikuussa ilmeisesti ajatuksella "käyttäkää jos sattuu olemaan hyötyä jollekin muulle". Projektin ylläpitäjä on merkinnyt sen minimaalisesti ylläpidettäväksi. Virallista julkaisuversiota ei ole tehty, jaossa on vain kehitysverio.
Moduulille on kirjoitettu vain yksi *issue*, joka liittyi lähinnä koodaus standardeihin (minor) ja sekin oli korjattu vuosi sitten.
Haluttu toiminto on sinänsä yksinkertainen, joten moduuli tuskin on mitenkään suuri tai sen lähdekoodi eroaisi omasta räätälöidystä …
> HUB-357: Open summary

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.news.default.yml
- config/sync/core.extension.yml
This change will bring new module "Maxlength" which is widely used in Drupal 7 sites, but it has an ported version to Drupal 8 too. Despite it's in beta2 phase, maintainer is recommending it for the use.
The module is not super big and not hooking into many things, so I consider this module safe from backend point of view. Only worrying part is the JS functionality, that's where most of the functionality is executed, but luckily we are trying to achieve here simple and not business critical things.
Module works basically as follows:
* I defines the standard help texts
* It hooks into element rendering adding JS attachments and CSS classes
* It specifies third party settings for widgets, these settings allows maintainer to specify which fields has maxlength functionality enabled. It has a …
> HUB-358: Summary limit

- CHANGELOG.md
- composer.json
- composer.lock
* Changes `composer.json`, to use tilde version range
> The ~ operator is best explained by example: ~1.2 is equivalent to >=1.2 <2.0.0, while ~1.2.3 is equivalent to >=1.2.3 <1.3.0. As you can see it is mostly useful for projects respecting semantic versioning. A common usage would be to mark the minimum minor version you depend on, like ~1.2 (which allows anything up to, but not including, 2.0). Since in theory there should be no backwards compatibility breaks until 2.0, that works well. Another way of looking at it is that using ~ specifies a minimum version, but allows the last digit specified to go up.
* Executed `composer update drupal/core --with-dependencies`
* Updates `CHANGELOG.md`
> HUB-441: Core update

- CHANGELOG.md
- config/sync/block.block.contactblock.yml
- config/sync/block.block.generalnews.yml
- config/sync/block.block.newsperdegreeprogramme.yml
- config/sync/block.block.newsperdegreeprogramme_2.yml
- config/sync/block.block.newsperdoctoralprogramme.yml
- config/sync/block.block.themesperusergroup.yml
- config/sync/core.entity_form_display.node.news.default.yml
- config/sync/core.entity_view_display.node.news.default.yml
- config/sync/field.field.node.news.field_user_group.yml
- config/sync/language/fi/block.block.newsperdoctoralprogramme.yml
- config/sync/language/sv/block.block.newsperdoctoralprogramme.yml
- modules/uhsg_news/src/Plugin/Block/NewsPerDegreeProgramme.php
- modules/uhsg_news/src/Plugin/Block/NewsPerDoctoralProgramme.php
- themes/uhsg_theme/templates/block/block--themes-per-user-group.html.twig
- themes/uhsg_theme/uhsg_theme.theme
- Adds user group to news (optional field). Note that this field does not affect the functionality at the moment. It will be needed later on when providing news to external systems and when adding user group grouping to guide search results.
- Displays news under the "Doctoral Candidates" tab on the front page matching the active degree programme when the active degree programme is of type `doctoral`. Note that the news user group does not affect this functionality.
- Displays news under the "Degree Students" tab on the front page matching the active degree programme when the active degree programme _is not_ of type `doctoral`. This is to prevent doctoral programme specific news to be displayed as non-doctoral degree programme specific news. It is ok, for now, to display all other news …
> HUB-454: News for doctoral candidates

- CHANGELOG.md
- config/sync/domain.record.guide_student_helsinki_fi.yml
- config/sync/domain.record.guide_teacher_helsinki_fi.yml
Local environment only supports http protocol. Dev and prod support
https. Domain tries to redirect domain content to https also on
localhost, resulting in a failure. This configuration change uses
variable URL scheme that will work dynamically based on the incoming
web request, thus making the redirects work correctly in http and https
enabled environments.
> HUB-481: Use variable domain URL scheme to support both http and https

- CHANGELOG.md
- package-lock.json
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/layout/_layout.scss
- Create a new article with a couple of text paragraphs.
- Insert a multicolumn table in one of the paragraphs (go overboard).
- Verify that the left column (paragraph title) will not get squashed anymore.
> HUB-483: Prevent wide content from squashing left column

- CHANGELOG.md
- modules/uhsg_feedback/uhsg_feedback.module
When sending email via the feedback form, the email title now reflects the site, and is now either:
"Feedback from Instructions for student"
OR
"Feedback from Instructions for teaching"
> HUB-614 - When sending email via the feedback form, the email title

- CHANGELOG.md
- modules/uhsg_news/uhsg_news.module
When using the scheduled publishing for bulletins, use the publish on time as the bulletin (news) created time.
> HUB-616: Use news publish on time as created time

- gulpfile.babel.js
- package-lock.json
- package.json
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/components/_misc.scss
- themes/uhsg_theme/templates/fields/field--node--field-theme-faq.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--eduviewer.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--office-hours.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--paragraph.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--theme-section.html.twig
Had to update the frontend build stack as the previous stack just failed with a ton of errors. Might be a good idea to test that one locally (as instructed in themes/uhsg_theme/README.md):
- cd to student_guide **repo root** (ie. **not** in the theme folder root)
- `npm install`
- `npm run gulp styleguide-update`
- `npm run gulp sass`
Shouldn't see any errors with the above. Created a followup ticket for further fixes and updates: https://jira.it.helsinki.fi/browse/HUB-682
Some css updates also resulted from the build stack update but they should all be safe (autoprefixer output changed a bit due to latest package versions).
The actual ticket related changes can be review from changes in files under
- `themes/uhsg_theme/sass/`
- `themes/uhsg_theme/templates/`
or by filtering the diff view …
> HUB-669: Heading level fix

- config/sync/core.entity_form_display.paragraph.paragraph.default.yml
- config/sync/core.entity_view_display.paragraph.paragraph.default.yml
- config/sync/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- config/sync/field.storage.paragraph.field_paragraph_faculty.yml
- config/sync/language/fi/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- config/sync/language/sv/field.field.node.article.field_article_faculty.yml
- config/sync/language/sv/field.field.node.news.field_news_faculty.yml
- config/sync/language/sv/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- modules/uhsg_article/uhsg_article.module
- themes/uhsg_theme/templates/paragraphs/paragraph--paragraph.html.twig
- themes/uhsg_theme/uhsg_theme.theme
Extends the Faculty feature introduced in https://github.com/UH-StudentServices/student_guide/pull/317 / https://jira.it.helsinki.fi/browse/HUB-370 to Paragraph-type paragraphs:
- Adds a Faculty field to Paragraph-paragraph form and view displays
- Populates the Paragraph-paragraph Degree programmes field on a presave hook based on Faculty field content
> HUB-646: Paragraph faculty selection

- config/sync/field.field.node.article.field_article_faculty.yml
- config/sync/field.field.node.news.field_news_faculty.yml
- config/sync/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- config/sync/language/fi/field.field.node.article.field_article_faculty.yml
- config/sync/language/fi/field.field.node.news.field_news_faculty.yml
- config/sync/language/fi/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- config/sync/language/sv/field.field.node.article.field_article_faculty.yml
- config/sync/language/sv/field.field.node.news.field_news_faculty.yml
- config/sync/language/sv/field.field.paragraph.paragraph.field_paragraph_faculty.yml
- gulpfile.babel.js
- package-lock.json
Updating the Faculty field description text in all languages and for all use cases: Instructions and Bulletin content types and the Paragraph paragraph.
Also updating npm package `acorn` to resolve a dependabot PR. And fixing gulpfile to allow a proper `watch`-task run (caused by gulp version update from 3 to 4 a while back but was then left unnoticed).
> HUB-687: Faculty texts

- composer.json
- composer.lock
* This patch will fix: "Either the path '/node/2363' is invalid or you do not have access to it." error that has been introduced in Drupal 8.8.x.
* This patch is not the final solution and needs to be monitored, but for now, it is acceptable to get translating working again.
> Add patch for translation nodes.

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/node.type.article.yml
- config/sync/node.type.news.yml
- config/sync/node.type.theme.yml
- config/sync/simple_sitemap.bundle_settings.default.node.article.yml
- config/sync/simple_sitemap.bundle_settings.default.node.news.yml
- config/sync/simple_sitemap.bundle_settings.default.node.theme.yml
- config/sync/simple_sitemap.custom_links.default.yml
- config/sync/simple_sitemap.settings.yml
- config/sync/simple_sitemap.variants.default_hreflang.yml
- config/sync/uhsg_role_auto_assign.settings.yml
This PR adds simple_sitemap-module to project and configures it to generate an xml sitemap with all News, Instructions and Theme content type nodes included.
- Wait for Drupal cron to run or run it manually with `drush cron --uri=[site_url]` (--uri parameter is required for proper sitemap urls)
- Go to [site_url]/sitemap.xml
> HUB-714: Xml sitemap

- README.md
- config/sync/domain.record.guide_student_helsinki_fi.yml
- config/sync/domain_alias.alias.guide_student_helsinki_fi_redirect.yml
- config/sync/domain_alias.alias.studies_helsinki_fi.yml
- config/sync/system.site.yml
- gulpfile.babel.js
- modules/uhsg_obar/src/Jwt.php
https://guide.student.helsinki.fi/ (old)
https://studies.helsinki.fi/ (new)
Changes in may 2020
There is a new domain set for student guide: studies-qa.it.helsinki.fi .
Guide will be sharing the studies domain which also hosts multiple other services
in the same root. Drupal is accessed via a proxy which reserves Drupal related
language prefixed paths to student guide. Teaching instructions still remain
in the old domain, which further complicates the setup.
The new domains are:
- local.studies-qa.it.helsinki.fi
- dev.studies-qa.it.helsinki.fi
- studies.helsinki.fi
NOTE: most of the changes are in the separate student_guide_infra repo.
> HUB-725 - Documented the new domains:

- CHANGELOG.md
- modules/uhsg_cookie_consent/uhsg_cookie_consent.info.yml
- modules/uhsg_cookie_consent/uhsg_cookie_consent.module
This PR limits the cookie consent banner to only appear on Teaching instructions domain as Student guide will start to show a cookie banner through obar.
- Open both http://local.guide.student.helsinki.fi/instructions and http://local.teaching.helsinki.fi/ohjeet on an incognito browser
- You should only see one cookie banner in both, Student guide providing it through obar
> HUB-728: Remove cookie banner from Student guide

- CHANGELOG.md
- config/sync/contact.form.feedback_form.yml
- config/sync/domain.config.guide_teacher_helsinki_fi.contact.form.feedback_form.yml
- modules/uhsg_feedback/uhsg_feedback.module
This PR updates global feedback email for the student guide and adds a domain config override to add a separate email for the teachers guide.
- Open both http://local.teaching.helsinki.fi/ohjeet and http://local.guide.student.helsinki.fi/ohjeet
- Send feedback from both sites
- Open mailhog: http://127.0.0.1:8025/ and check the recipient is correct for both emails:
- Student guide: studies@helsinki.fi
- Teachers guide: guidance-coordination@helsinki.fi
> HUB-710: Feedback email

- CHANGELOG.md
- config/sync/field.storage.node.field_user_group.yml
- config/sync/language/fi/field.storage.node.field_user_group.yml
- config/sync/language/sv/field.storage.node.field_user_group.yml
This PR adds a new user group otion 'Open University' for Instructions, Themes and Bulletins. This is to allow open university to start adding help content to the site, so there's no need to make this change visible elsewhere on the site at this point.
> HUB-772: Open university user group

- CHANGELOG.md
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/components/_textarea.scss
This PR updates styles for content links when inside tables to improve accessibility. These same changes were introduced for content area links in https://github.com/UH-StudentServices/student_guide/pull/351 but those changes didn't apply for links inside tables.
> HUB-779: Content table link styles

- CHANGELOG.md
- modules/uhsg_search/js/uhsgSearch.js
- modules/uhsg_search/uhsg_search.module
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/js/degreeProgrammeFilter.js
- themes/uhsg_theme/js/degreeProgrammeSwitcher.js
- themes/uhsg_theme/js/otherEducationProviderSwitcher.js
- themes/uhsg_theme/sass/components/_degree-programme-switcher.scss
- themes/uhsg_theme/sass/components/_misc.scss
- themes/uhsg_theme/sass/components/_other-education-provider-switcher.scss
- themes/uhsg_theme/sass/components/_search.scss
- themes/uhsg_theme/templates/block/block--views-block--degree-programmes-block-1.html.twig
- themes/uhsg_theme/templates/block/block--views-block--other-education-providers-block-1.html.twig
- themes/uhsg_theme/templates/views/views-view-grouping.html.twig
- themes/uhsg_theme/templates/views/views-view-list.html.twig
- translations/fi.po
- translations/sv.po
This PR fixes multiple accessibility issues in degree programme selection and site search form for both the student guide and teachers guide.
- Proper semantic ordering of heading tags and removing heading tags where they were misleading for screen readers.
- Making the toggle element a button and adding aria-attributes to better inform screen readers of its state and relations.
- Improving the degree programme filtering input to better instruct screen reader users of what it does and how to use it by adding more informative labels and descriptions, and adding a aria-live region to inform of current result count.
- Improving the site search form by adding an aria-label to submit button for screen readers and allowing native browser validation for required keyword field (this will …
> HUB-757 & HUB-774: Degree programme selection accessibility improvements

- CHANGELOG.md
- themes/uhsg_theme/js/degreeProgrammeSwitcher.js
- themes/uhsg_theme/js/otherEducationProviderSwitcher.js
This PR updates the degree programme and other education provider selection elements to close when focus is set outside of them. This is to avoid a use case where a focused element is behind an open selection container as a result of keyboard navigation.
> HUB-756: Degree programme selection - close when focus goes out

- CHANGELOG.md
- themes/uhsg_theme/templates/misc/pager.html.twig
This PR updates the pager markup with accessible indicators for the link pointing to current page.
> HUB-758: Paging a11y

- CHANGELOG.md
- themes/uhsg_theme/templates/node/node--constrained.html.twig
This PR removes the link wrapper from search result ingress text. The title already has the link and having it on the ingress as well results in consecutive identical links which is misleading / confusing to many assistive technologies.
> HUB-762: Search result double links away

- CHANGELOG.md
- themes/uhsg_theme/uhsg_theme.theme
This PR adds a `lang`-attribute to language switcher links for proper screen reader pronunciation.
> HUB-759: Language switcher a11y

- CHANGELOG.md
- config/sync/language/fi/uhsg_service_provider_details.settings.yml
- config/sync/language/sv/uhsg_service_provider_details.settings.yml
- config/sync/uhsg_service_provider_details.settings.yml
This PR updates the footer copyright year to 2020 (yeah I know, better late than never 😄 ). This only affects the teachers guide as student guide has the obar.
> HUB-748: Footer copyright year

- CHANGELOG.md
- config/sync/editor.editor.filtered_html.yml
This PR adds `zip` to editor_file allowed extensions. This allows zip files to be uploaded as content attachments.
> HUB-789: Allow zip attachments

- CHANGELOG.md
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/js/degreeProgrammeSwitcher.js
- themes/uhsg_theme/js/otherEducationProviderSwitcher.js
- themes/uhsg_theme/sass/components/_degree-programme-switcher.scss
- themes/uhsg_theme/sass/components/_other-education-provider-switcher.scss
This PR updates the way degree programme and other education provider (teachers guide) selections behave on **mobile**:
- Selection box no longer opens on top of content but instead is part of the page flow pushing the rest of the page content down - This overcomes a usability issue where screen reader navigation might end up focusing on an element behind the selection box (for example iOS + Safari + VoiceOver where normal focus event's aren't triggered so there's actually no way of detecting when that happens).
- Selection box is no longer automatically closed when focus or click is set outside of the box - This might cause a very confusing page scroll when the closing box changes the document height.
> HUB-785: Degree programme and other education provider selection mobile a11y

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/editor.editor.filtered_html.yml
- config/sync/filter.format.filtered_html.yml
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/components/_textarea.scss
This PR adds a new contrib module `responsive_table_filter` and activates a new text format filter to wrap all content tables into a responsive container. This also removes the forced bold text on the first table column to not make it appear as a heading cell unless it actually is one.
> HUB-770: Responsive tables

- CHANGELOG.md
- modules/uhsg_rest/src/Plugin/rest/resource/DegreeProgrammeResource.php
…ub.com/UH-StudentServices/student_guide/pull/383/files ).
Anonynous visitors would get a fatal error at https://studies.helsinki.fi/ohjeet/api/v1/degree-programme?_format=json :
LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\rest\ResourceResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (line 154 of /var/www/html/build/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).
Disablong access check permission is the simple fix here, and is secure because the query is only fetching node counts.
More info: …
> HUB-828 - Fixing JSONAPI regression related to HUB-804

- CHANGELOG.md
- composer.json
- composer.lock
This PR applies a Drupal core patch to fix a bug where the first item of all the Node revision list pages was always marked as the currently active version, making it impossible to open or revert those versions.
> HUB-805: Revision lists fix

- CHANGELOG.md
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/components/_header_obar.scss
- themes/uhsg_theme/sass/variables/_variables.scss
This PR updates styles for the obar container:
- Update background color to match obar.
- Update container minimum height closer to current obar heights in different breakpoints. Also minimum height is now only active when the container is empty to allow the actual obar content to dictate the height when it's loaded.
> HUB-689: Obar container background color and height

- modules/uhsg_sisu/src/Services/SisuService.php
- modules/uhsg_sisu/src/Services/StudyRightsService.php
- modules/uhsg_user_sync/src/SamlAuth/UserSyncSubscriber.php
It turns out that apparently the switch from Guzzle to Curl for Sisu queries was actually incomplete, and there were checks for an Response-object when the variable was in fact an array. Even though the variable in the data was as expected, this legacy check caused studyright fetches to basically always fail.
To fix this, I documented the return type in SisuService to an array, and it's also auto-converted to array in the places where its used in our custom code.
Other changes
-----------------------
* The problems were found by adding several new debug log entries for Sisu-queries, which can be enabled by adding to settings.local.php this:
$settings['uhsg_sisu_log_responses'] = TRUE;
* This setting has been activated on QA and my own local env.
* Initialized a few vars to avoid notices. …
> HUB-803 - Part II

- modules/uhsg_active_degree_programme/src/ActiveDegreeProgrammeService.php
- modules/uhsg_degree_programme_filtering/uhsg_degree_programme_filtering.module
* Add possibility to return all article contents without any degree_programme filtering by defining degree_programme either as a get-parameter or header info 'x-degree-programme'.
This will both allow siteimprove to see all content, and aswell content editors to see all content to see faster what content needs updating.
> HUB-800 - Add possibility to define degree_programme as 'all' 

- CHANGELOG.md
- composer.lock
This PR updates video_embed_unitube to version 1.0-alpha2 for www2-subdomain support on Unitube video urls.
> HUB-849: Unitube www2

- CHANGELOG.md
- modules/uhsg_sisu/src/Services/StudyRight/StudyRight.php
* We have special cases with studyrights where they have added more codes to sisu codes compared to oodi codes. This means we need to strip the end of the code and return the first part only. This is cause the instructions in Guide has been bundled together.
The code returned in Sisu is like: 220102-03230
We will need to combine the codes for these:
```
'320018', // Special Doctors 5 year education.
'320019', // Special Doctors 6 year education.
'320006', // Special dentistry education.
'220102' // Professional Licenciates.
```
> HUB-776 - Handle special codes with sisu transfer.

- CHANGELOG.md
- themes/uhsg_theme/js/tabs.js
- themes/uhsg_theme/templates/block/block--themes-per-user-group.html.twig
- themes/uhsg_theme/uhsg_theme.libraries.yml
This PR restores a feature where deep links (aka. anchor links) that target an element inside a tabbed container will now properly activate the tab and then scroll the window to that anchor. This feature used to work before the accessibility updates to frontpage theme container where the whole tabbing mechanism had a major overhaul. Unfortunately the `a11y-accordion-tabs`-library didn't have a built-in support for this so we had to implement the following:
1. Register a mutation observer to find out when the tab container receives a `is-initialized` css class to indicate the tabbing script has done it's magic.
2. Activate the proper tab.
3. And finally scroll the window to given anchor element.
> HUB-848: Deep links in tabbed containers

- CHANGELOG.md
- composer.json
- composer.lock
This PR fixes a translation import error that surfaced when `json_api_imagestyles`-module was added. The root cause was in Drupal cause and luckily a patch was found (https://www.drupal.org/project/drupal/issues/2449895). This also fixes another marginally visible error where `/admin/content/files` view would error out if accessed within a temporary file lifetime after a translation file import.
> HUB-860: Translation import error

- CHANGELOG.md
- config/sync/core.extension.yml
- modules/uhsg_translations/README.txt
- modules/uhsg_translations/src/Helpers/TranslationHelper.php
- modules/uhsg_translations/uhsg_translations.info.yml
- modules/uhsg_translations/uhsg_translations.install
- modules/uhsg_translations/uhsg_translations.services.yml
Adding and enabling uhsg_translations, which is mostly a copy/fork of uhc_translations (courses).
The readme.txt has been updated with a section about deployment/releases, as the translation import used to be part of the manual steps.
NOTE: comparable PR for new Silta repo is at:
https://github.com/wunderio/client-fi-uh-guide/pull/76
> HUB-846 - Adding and enabling uhsg_translations

- CHANGELOG.md
- modules/uhsg_themes/src/Plugin/Block/ThemesReferencingInstructions.php
- modules/uhsg_translations/uhsg_translations.install
- themes/uhsg_theme/css/style.css
- themes/uhsg_theme/sass/components/_breadcrumbs.scss
- themes/uhsg_theme/sass/components/_index.scss
- themes/uhsg_theme/sass/components/_tag-list.scss
- themes/uhsg_theme/sass/layout/_layout.scss
- themes/uhsg_theme/sass/objects/_button.scss
- themes/uhsg_theme/sass/style.scss
- themes/uhsg_theme/sass/variables/_variables.scss
- themes/uhsg_theme/templates/fields/field--field-article-paragraph.html.twig
- themes/uhsg_theme/templates/node/node--article--full.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--eduviewer.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--office-hours.html.twig
- themes/uhsg_theme/templates/paragraphs/paragraph--paragraph.html.twig
This PR updates the layout and styles mainly for the Instruction node page, but does include some global changes:
- "The instruction belongs to the following themes" link list moved from right to left column, and list heading updated
- Anchor links moved from full page container to main column container to follow the main content flow
- Column widths and gutters updated to follow Studies service common styleguide
- Action button styles updated
- Paragraph headings moved from side column to main column
> HUB-720: Instruction page UI updates

- CHANGELOG.md
- modules/uhsg_samlauth/src/AttributeParser.php
This PR updates the way we process the `schacPersonalUniqueCode`-attribute from samlauth. For now this attribute has always populated UH specific id values but that is about to change in the future. We need to make sure the value has a prefix of `urn:schac:personalUniqueCode:int:studentID:helsinki.fi:` before returning the id part.
> HUB-870: Updating the way we process the schacPersonalUniqueCode-attribute

- config/sync/language/sv/field.field.node.theme.field_theme_articles.yml
Pushing a manual production change to code.
> HUB-872: Adding a missing sv translation for field_theme_articles label.
